version: '3'

services:
  mysql:
    container_name: symfony_mysql
    image: mysql:5.7
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    networks:
      - symfony_app
    volumes:
      - db_data:/var/lib/mysql
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - symfony_app
    depends_on:
      - mysql
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

networks:
  symfony_app:

volumes:
  db_data:

